ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true
    odom0: diffbot_base_controller/odom # Chủ đề odometry
    odom0_config: [true, true, false,
                    false, false, true,
                    false, false, false,
                    false, false, false,
                    false, false, false]
    odom0_differential: false
    odom0_relative: false
    imu0: imu/mpu6050 # Chủ đề IMU
    imu0_config: [false, false, false,
                    true, true, true,
                    true, true, true,
                    false, false, false,
                    false, false, false]
    imu0_differential: false
    imu0_relative: false
    imu0_remove_gravitational_acceleration: true
    publish_tf: true
    publish_frequency: 30.0
    # Ma trận hiệp phương sai (điều chỉnh những giá trị này!)
    odom0_pose_covariance: [0.01, 0.0, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0.01, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0.0, 99999.0, 0.0, 0.0, 0.0,
                            0.0, 0.0, 0.0, 99999.0, 0.0, 0.0,
                            0.0, 0.0, 0.0, 0.0, 99999.0, 0.0,
                            0.0, 0.0, 0.0, 0.0, 0.0, 0.1]
    imu0_pose_covariance: [99999.0, 0.0, 0.0, 0.0, 0.0, 0.0,
                           0.0, 99999.0, 0.0, 0.0, 0.0, 0.0,
                           0.0, 0.0, 99999.0, 0.0, 0.0, 0.0,
                           0.0, 0.0, 0.0, 0.01, 0.0, 0.0,
                           0.0, 0.0, 0.0, 0.0, 0.01, 0.0,
                           0.0, 0.0, 0.0, 0.0, 0.0, 0.01]
    imu0_twist_covariance: [0.0001, 0.0, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0.0001, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0.0, 0.0001, 0.0, 0.0, 0.0,
                            0.0, 0.0, 0.0, 99999.0, 0.0, 0.0,
                            0.0, 0.0, 0.0, 0.0, 99999.0, 0.0,
                            0.0, 0.0, 0.0, 0.0, 0.0, 99999.0]